{
 "title": "Minitwit",
 "time": { "from": "2022-03-27T15:55:26.624Z", "to": "2022-03-27T17:15:26.640Z" },
 "panels": [
  {
   "title": "Avg response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "responseTime_sum / responseTime_count "
    }
   ]
  },
  {
   "title": "New users in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "NewUserInProgress" }
   ]
  },
  {
   "title": "Request in progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Tweet duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "TweetOperationDuration_bucket" }
   ]
  },
  {
   "title": "Cpu time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])",
     "legendFormat": "{{cpu}}--{{mode}}"
    }
   ]
  },
  {
   "title": "Total new user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "TotalUsers" }
   ]
  }
 ]
}