# This is a basic workflow to help you get started with Actions

name: Latex to pdf

# Controls when the workflow will run
on:
  push:
    tags:        
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Clone frontend
        run: git clone https://github.com/hvsio/minitwit_FE.git
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: _main.tex
          working_directory: ./report
          name: report
     
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./report/_main.pdf
            ./minitwit_FE/
          tag_name: ${{ env.RELEASE_VERSION }}
      
